project:
  type: website
  output-dir: docs

website:
  title: "情報処理演習"
  navbar:
    left:
      - href: index.qmd
        text: ホーム

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true