---
title: "情報処理演習"
toc: false
---

千葉大学 国際教養学部

担当教員：[ニッタ ジョエル](https://www.joelnitta.com)

## 概要

近年、私たちの生活のあらゆる場面において「データ」が活用されるようになっています。したがって、データを適切に整理し、データに潜むメッセージを読み解くスキルが現代社会において必須となっています。本授業では、データ構造の基本とデータ解析に必要なスキルを「R」というプログラミング言語を通じて学びます。また、生成AIの原理と正しい使い方についても学びます。

## 教科書

- [R for Data Science (2nd Edition) by Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund](https://r4ds.hadley.nz/)
  - 英語版はオンラインで無料で利用可能 [https://r4ds.hadley.nz/](https://r4ds.hadley.nz/)
  - 日本語版は[アマゾン](https://www.amazon.co.jp/R%E3%81%A7%E3%81%AF%E3%81%98%E3%82%81%E3%82%8B%E3%83%87%E3%83%BC%E3%82%BF%E3%82%B5%E3%82%A4%E3%82%A8%E3%83%B3%E3%82%B9-%E7%AC%AC2%E7%89%88-Hadley-Wickham/dp/4814400772/ref=sr_1_2?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&crid=38I6KDKKIV16O&dib=eyJ2IjoiMSJ9.GGF0L1q-Erx9HU27rscRki94Ao9GXZ5y2HVFdEev4zxG1OTnzPpbg-mjmrzdKgeFzt1hC_NBl3doKyAasQaPGTZCi-OU_aKSZ92B_Jb5wmua9KFy3v5UPz0PQAMonejSVV660k3GOmLZo2il--e6dr0xcuhnABRob_ZQ_SP4i89KX-EtaiytgmFSsGyZfjLCHe4mhXgpnc3kl4yXZSFvx-WwDLOGM4BBrxDULLWvVHbiFXTbdFKKoyTHnGHMo2b-2gH-pJtvNNrbvyfapYofa71PdrY0p6HPWpZ2_HI2Gn0.jtDTN8tC0wccGCgPGCZmNMKsX0PRN3vXFMTo4JbMnWw&dib_tag=se&keywords=R+for+Data+Science+%282nd+Edition%29&qid=1725332552&sprefix=r+for+data+science+2nd+edition+%2Caps%2C255&sr=8-2)など

- 課題範囲（毎週のリーディング）のみPDFをMoodleで配布予定

## 教室

G1-501 情報処理演習室

## スケジュール

毎週のリーディングは講義の**前に**読んでください。下のリンクは英語ですが、Moodleに日本語版のPDFがあります。

（すべての講義に録画はありません）

- 第１回（2025-10-07）: **ガイダンス、RとRStudioのインストール、R入門（１）**
  - [スライド](day1/index.qmd)
  - リーディング: [R4DS Introduction](https://r4ds.hadley.nz/intro)
- 第２回（2025-10-14）: **R入門（２）**
  - [スライド](day2/index.qmd)
  - リーディング: [R4DS Chapter 2 (Workflow: Basics)](https://r4ds.hadley.nz/workflow-basics)
- 第３回（2025-10-21）: **プロジェクトの整理とデータの読み込み**
  - [スライド](day3/index.qmd)
  - リーディング
    - [R4DS Chapter 6 (Workflow: Scripts and projects)](https://r4ds.hadley.nz/workflow-scripts)
    - [R4DS Chapter 7 (Data Import)](https://r4ds.hadley.nz/data-import)
- 第４回（2025-10-28）: **データの整理（１）**
  - [スライド](day4/index.qmd)
  - リーディング: [R4DS Chapter 3 (Data transformation)](https://r4ds.hadley.nz/data-transform)
- 第５回（2025-11-04）: **データの整理（２）**
  - [スライド](day5/index.qmd)
  - リーディング
    - [R4DS Chapter 3 (Data transformation: Groups)](https://r4ds.hadley.nz/data-transform#groups)
    - [R4DS Chapter 19 (Joins: 19.1 - 19.4)](https://r4ds.hadley.nz/joins)
- 第６回（2025-11-11）: **データの可視化（１）**
  - [スライド](day6/index.qmd)
- 第７回（2025-11-18）: **データの可視化（２）、AIによるプログラミング**
  - [スライド](day7/index.qmd)
- オンデマンド回
  - [スライド](on-demand/index.qmd)
  - [録画](https://youtu.be/ok837FBoEI8)

## オフィスアワー

予約制（<joelnitta@chiba-u.jp>までメールにてご連絡ください）。対面・非対面での相談をご希望とご都合に合わせて対応いたします。

## リンク

- [シラバス](https://syllabus.gs.chiba-u.jp/2025/101101101076000/Z011202901/ja_JP)
- [Moodle](https://moodle.gs.chiba-u.jp/moodle/course/view.php?id=44299)
